---
- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Brew Cask
  command: brew install caskroom/cask/brew-cask

- name: Upgrade Brew Cask
  command: brew cask upgrade

- name: Install Casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
    update_homebrew: yes
  with_items:
    - '{{ cask_installs }}'
  ignore_errors: yes


- name: Install Commandline Utilities
  homebrew:
    pkg: '{{ item }}'
    state: latest
    update_homebrew: yes
  with_items:
    - '{{ must_haves }}'

- name: Cleanup Brew
  command: brew cask cleanup